# Read the Docs configuration file
# See: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - pip install --upgrade pip

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true

python:
  install:
    - requirements: requirements-docs.txt

formats:
  - htmlzip
  - pdf

# MkDocs-only configuration. Add Sphinx section later if migration needed.
