site_name: BloomTrip Documentation
site_description: >
  Open-source travel planning platform powered by Azure AI Search, Azure OpenAI, and multi-source enrichment.
  RAG-based itinerary generation, smart caching, and TOS-compliant integration with open and partner data.
site_url: https://bloomtripbeta.readthedocs.io
site_dir: ../site
repo_url: https://github.com/dhont/bloomtrip
repo_name: bloomtrip
edit_uri: edit/main/docs/

# Because this config now lives inside the docs/ directory, set docs_dir explicitly.
docs_dir: .

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.suggest
    - search.highlight
    - toc.integrate
  custom_dir: overrides

extra_css:
  - css/mermaid-theme.css

# Load Mermaid runtime (render diagrams client-side). PDF export may not execute JS; consider build-time plugin later.
extra_javascript:
  - https://unpkg.com/mermaid@10.9.3/dist/mermaid.min.js
  - js/mermaid-init.js

plugins:
  - search

markdown_extensions:
  - admonition
  - def_list
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - toc:
      permalink: true

nav:
  - Project Overview: 01_project-overview.md
  - Requirements: 02_requirements-spec.md
  - Solution Design: 04_solution-design.md
  - Azure Feasibility: feasibility-azure.md
  - Market Analysis: 05_market-analysis.md
  # Market Comparison doc not yet created; removed from nav
  - Positioning & Messaging: positioning-and-messaging.md
  - One-Pager: one-pager.md
  - Home: index.md
  - Getting Started: getting_started.md
  - Architecture:
    - Overview: architecture/README.md
    - Azure Architecture: architecture/azure_overview.md
    - RAG Flow Diagram: architecture/rag_flow.md
  - Specs:
    - Petal Schema: specs/petal_schema.md
    - Trip Schema: specs/trip_schema.md
    - User Profile Schema: specs/user_profile_schema.md
    - API Endpoints: specs/api_endpoints.md
  - Caching & RAG: rag_pipeline.md
  - Compliance: compliance.md
  - Operations:
    - Monitoring & Logging: operations/monitoring.md
    - Deployment: operations/deployment.md
  - Roadmap: roadmap.md
  - Mockups: 
    - Overview: mockups/README.md
  - Bucharest E-Bike Weekend: mockups/weekend-bucharest-ebike.md
  - Search Refinement Mockup: mockups/search-refinement.md
  - Itinerary Map Page: mockups/itinerary-map-page.md
  - Itinerary Refinement Detail: mockups/itinerary-refinement-detail.md
  - Trip In Progress View: mockups/trip-in-progress.md
  - Navigation Picker: mockups/navigation-picker.md
  - Post-Trip Feedback Survey: mockups/trip-feedback-survey.md
  - User Dashboard: mockups/user-dashboard.md
  - On-Trip Mode Transition: mockups/on-trip-mode-transition.md
  - Trip Builder Start: mockups/trip-builder-start.md
  - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dhont/bloomtrip
      name: GitHub
copyright: "© 2025 BloomTrip"